CREATE TABLE Person (
                        id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        username varchar(100) NOT NULL,
                        year_of_birth int NOT NULL,
                        password varchar(100) NOT NULL
);

INSERT INTO Person(username, year_of_birth, password) VALUES ('user1', 1999, 'password1');
INSERT INTO Person(username, year_of_birth, password) VALUES ('user2', 1999, 'password2');